[package]
name = "merger_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
linked-hash-map = "0"
clap = { version = "4.0", features = ["derive"] }
csv = "1.3.0"
anyhow = "1.0.86"
itertools = "0.13.0"

